# Generated by Django 6.0.7 on 2026-07-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalafo_app', '0002_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
